services:
  mongodb:
    image: mongo:latest
    container_name: viartic
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_ROOT_DB: ${MONGODB_DB}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
